version: "3.3"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.talk.rule=Host(`talk.wuhanstudio.uk`)"
        - "traefik.http.routers.talk.entrypoints=web"
        - "traefik.http.services.talk.loadbalancer.server.port=80"
        # TLS
        - "traefik.http.routers.talks.rule=Host(`talk.wuhanstudio.uk`)"
        - "traefik.http.routers.talks.entrypoints=websecure"
        - "traefik.http.routers.talks.tls.certresolver=myhttpchallenge"
        # Redirect
        - "traefik.http.routers.talk.middlewares=https_redirect"
        - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
